services:
  - type: web
    name: car-flip-analyzer
    env: python
    buildCommand: bash render-build.sh
    startCommand: uvicorn backend_api:app --host 0.0.0.0 --port 10000
    envVars:
      - key: SERVER
        value: carflip-db.crqg0ema4vx8.us-east-2.rds.amazonaws.com
      - key: DATABASE
        value: cars
      - key: USERNAME
        value: admin
      - key: PASSWORD
        value: your_actual_password
